/*
 * common_err_code_c.h
 *
 * History:
 *    8/31/2020 - [Zhi He] created file
 *
 * Copyright (C) 2022 Ambarella International LP
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#ifndef __COMMON_ERR_CODE_C_H__
#define __COMMON_ERR_CODE_C_H__

#ifdef __cplusplus
extern "C" {
#endif

// check bits definitions
typedef struct {
    unsigned int code:16;
    unsigned int category:8;
    unsigned int handling:4;
    unsigned int severity:3; // severity
    unsigned int is_error:1; // indicate whether it's error or not
} common_error_code_t;


// error indicator
#define CEC_INDI 0x80000000

// error severity
#define CEC_SV_MASK 0x70000000
#define CEC_SV_SHIFT 28

#define CEC_SV_FAFAL 0x60000000
#define CEC_SV_CRITICAL 0x50000000
#define CEC_SV_WARNING 0x30000000
#define CEC_SV_MAJOR 0x20000000
#define CEC_SV_MINOR 0x10000000

// error handling
#define CEC_HD_MASK 0x0F000000
#define CEC_HD_SHIFT 24

#define CEC_HD_ABORT 0x0C000000
#define CEC_HD_RETRY 0x0A000000
#define CEC_HD_RECOVERY 0x06000000
#define CEC_HD_CONCEALMENT 0x04000000

// error category
#define CEC_CAT_MASK 0x00FF0000
#define CEC_CAT_SHIFT 16

// bad setting, not avaiable, failure
#define CEC_CAT_SW_BADSET 0x00010000
#define CEC_CAT_SW_NOTAVL 0x00020000
#define CEC_CAT_SW_FAILURE 0x00030000

#define CEC_CAT_HW_BADSET 0x00040000
#define CEC_CAT_HW_NOTAVL 0x00050000
#define CEC_CAT_HW_FAILURE 0x00060000

#define CEC_CAT_DSP_BADSET 0x00070000
#define CEC_CAT_DSP_NOTAVL 0x00080000
#define CEC_CAT_DSP_FAILURE 0x00090000

#define CEC_CAT_VP_BADSET 0x000A0000
#define CEC_CAT_VP_NOTAVL 0x000B0000
#define CEC_CAT_VP_FAILURE 0x000C0000

#define CEC_CAT_NET_BADSET 0x00110000
#define CEC_CAT_NET_NOTAVL 0x00120000
#define CEC_CAT_NET_FAILURE 0x00130000

#define CEC_CAT_SEC_FAILURE 0x00140000
#define CEC_CAT_SEC_ATTACK 0x00150000

#define CEC_CAT_MEM_VIOLATION 0x00160000
#define CEC_CAT_MEM_BAD_ADDR 0x00170000
#define CEC_CAT_MEM_MAP_FAILED 0x00180000

// sw
#define CEC_BAD_PARAMS 0x00000100
#define CEC_OUT_OF_RANGE 0x00000101
#define CEC_BAD_STATE 0x00000102
#define CEC_NO_MEMORY 0x00000103
#define CEC_NOT_SUPPORTED 0x00000104
#define CEC_OPEN_FILE_FAILED 0x00000105
#define CEC_CORRUPTED_FILE 0x00000106
#define CEC_CORRUPTED_DATA 0x00000107
#define CEC_INTERNAL_BUG 0x00000108
#define CEC_LACK_OF_RESOURCE 0x00000109
#define CEC_CHECK_LICENSE_FAILED 0x0000010A
#define CEC_NOT_MATCHED_VERSION 0x0000010B
#define CEC_READ_FILE_FAILED 0x0000010C
#define CEC_WRITE_FILE_FAILED 0x0000010D
#define CEC_STORE_FILE_FAILED 0x0000010E
#define CEC_NOT_EXPECTED 0x0000010F
//#define CEC_INTERRUPT 0x00000110
#define CEC_NOT_FOUND 0x00000111

// hw io
#define CEC_OPEN_IO_FAILED 0x00000200
#define CEC_READ_IO_FAILED 0x00000201
#define CEC_WRITE_IO_FAILED 0x00000202
#define CEC_CTRL_IO_FAILED 0x00000203

// dsp, iav
#define CEC_OPEN_IAV_FAILED 0x00000300
#define CEC_READ_IAV_FAILED 0x00000301
#define CEC_WRITE_IAV_FAILED 0x00000302
#define CEC_DSP_ASSERTION 0x00000303
#define CEC_CTRL_IAV_FAILED 0x00000304

// vp, cavalry
#define CEC_OPEN_VP_FAILED 0x00000400

// net
#define CEC_LISTEN_FAILED 0x00000500
#define CEC_ACCEPT_FAILED 0x00000501
#define CEC_CONNECT_FAILED 0x00000502
#define CEC_SEND_FAILED 0x00000503
#define CEC_RECV_FAILED 0x00000504
#define CEC_NEGOTIATION_FAILED 0x00000505

#define CEC_SSL_FAILED 0x00000506
#define CEC_BIND_FAILED 0x00000507
#define CEC_SELECT_FAILED 0x00000508
#define CEC_URL_RESOLVE_FAILED 0x00000509

//memory
#define CEC_MEM_VIOLATION 0x00000600
#define CEC_MEM_SEG_FAULT 0x00000601
#define CEC_MEM_BUS_ERROR 0x00000602
#define CEC_MEM_BAD_ADDR 0x00000603
#define CEC_MEM_MAP_FAILED 0x00000604
#define CEC_MEM_UNMAP_FAILED 0x00000605

//security
#define CEC_AUTH_FAILED 0x00000D00
#define CEC_NOT_VALID_PUBKEY 0x00000D01
#define CEC_NOT_VALID_PRIKEY 0x00000D02
#define CEC_NOT_VALID_TOKEN 0x00000D03
#define CEC_NOT_VALID_CERT 0x00000D04
#define CEC_NOT_VALID_SIGNATURE 0x00000D05
#define CEC_SIGN_FAILED 0x00000D06
#define CEC_WRONG_PASSPHRASE 0x00000D07
#define CEC_DENY_SERVICE 0x00000D08
#define CEC_GEN_KEY_FAILED 0x00000D09
#define CEC_DERIVE_KEY_FAILED 0x00000D0A
#define CEC_CRYPTO_COMPUTING_FAILED 0x00000D0B

#define CEC_VER_ROLLBACK_DETECTED 0x00000D80
#define CEC_REPLAY_DETECTED 0x00000D81
#define CEC_FLOODING_DETECTED 0x00000D82
#define CEC_LICENSE_CLONE_DETECTED 0x00000D83
#define CEC_MAN_IN_MIDDLE_DETECTED 0x00000D84

// not error code
#define CEC_PEER_CLOSE 0x00000C00
#define CEC_COMPLETE 0x00000C01
#define CEC_TRY_AGAIN 0x00000C02
#define CEC_NOT_MEET_REQUIREMENT 0x00000C03
#define CEC_NOT_FOUND_SKIP 0x00000C04
#define CEC_INTERRUPT 0x00000C05
#define CEC_SKIP_DUPLICATED 0x00000C06
#define CEC_NOT_NEEDED_SKIP 0x00000C07
#define CEC_HANDLE_MSG 0x00000C08

#define CECODE(indicator, severity, handling, cate, code) \
    (indicator | severity | handling | cate | code)




#define COM_ECODE_OK 0

#define COM_ECODE_BAD_PARAMS CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_RETRY, CEC_CAT_SW_BADSET, CEC_BAD_PARAMS)
#define COM_ECODE_OUT_OF_RANGE CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_BADSET, CEC_OUT_OF_RANGE)
#define COM_ECODE_BAD_STATE CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_BADSET, CEC_BAD_STATE)
#define COM_ECODE_NO_MEMORY CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_NO_MEMORY)
#define COM_ECODE_NOT_SUPPORTED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_BADSET, CEC_NOT_SUPPORTED)
#define COM_ECODE_OPEN_FILE_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_NOTAVL, CEC_OPEN_FILE_FAILED)
#define COM_ECODE_CORRUPTED_FILE CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_CORRUPTED_FILE)
#define COM_ECODE_CORRUPTED_DATA CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_CORRUPTED_DATA)
#define COM_ECODE_INTERNAL_BUG CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_INTERNAL_BUG)
#define COM_ECODE_LACK_OF_RESOURCE CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_LACK_OF_RESOURCE)

#define COM_ECODE_CHECK_LICENSE_FAILED CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_CHECK_LICENSE_FAILED)
#define COM_ECODE_NOT_MATCHED_VERSION CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_NOT_MATCHED_VERSION)

#define COM_ECODE_READ_FILE_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_NOTAVL, CEC_READ_FILE_FAILED)
#define COM_ECODE_WRITE_FILE_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_NOTAVL, CEC_WRITE_FILE_FAILED)
#define COM_ECODE_STORE_FILE_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_NOTAVL, CEC_STORE_FILE_FAILED)

#define COM_ECODE_NOT_EXPECTED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_NOT_EXPECTED)
//#define COM_ECODE_INTERRUPT CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_INTERRUPT)
#define COM_ECODE_NOT_FOUND CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SW_FAILURE, CEC_NOT_FOUND)

#define COM_ECODE_OPEN_IO_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_HW_BADSET, CEC_OPEN_IO_FAILED)
#define COM_ECODE_READ_IO_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_HW_FAILURE, CEC_READ_IO_FAILED)
#define COM_ECODE_WRITE_IO_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_HW_FAILURE, CEC_WRITE_IO_FAILED)
#define COM_ECODE_CTRL_IO_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_HW_FAILURE, CEC_CTRL_IO_FAILED)

#define COM_ECODE_OPEN_IAV_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_DSP_NOTAVL, CEC_OPEN_IAV_FAILED)
#define COM_ECODE_READ_IAV_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_DSP_FAILURE, CEC_READ_IAV_FAILED)
#define COM_ECODE_WRITE_IAV_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_DSP_FAILURE, CEC_WRITE_IAV_FAILED)
#define COM_ECODE_CTRL_IAV_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_DSP_FAILURE, CEC_CTRL_IAV_FAILED)
#define COM_ECODE_DSP_ASSERTION CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_DSP_FAILURE, CEC_DSP_ASSERTION)

#define COM_ECODE_OPEN_VP_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_VP_NOTAVL, CEC_OPEN_VP_FAILED)

#define COM_ECODE_LISTEN_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_RETRY, CEC_CAT_NET_NOTAVL, CEC_LISTEN_FAILED)
#define COM_ECODE_ACCEPT_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_RETRY, CEC_CAT_NET_NOTAVL, CEC_ACCEPT_FAILED)
#define COM_ECODE_CONNECT_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_RETRY, CEC_CAT_NET_NOTAVL, CEC_CONNECT_FAILED)
#define COM_ECODE_SEND_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_NET_FAILURE, CEC_SEND_FAILED)
#define COM_ECODE_RECV_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_NET_FAILURE, CEC_RECV_FAILED)
#define COM_ECODE_NEGOTIATION_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_NET_FAILURE, CEC_NEGOTIATION_FAILED)
#define COM_ECODE_SSL_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_NET_FAILURE, CEC_SSL_FAILED)
#define COM_ECODE_BIND_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_NET_FAILURE, CEC_BIND_FAILED)
#define COM_ECODE_SELECT_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_NET_FAILURE, CEC_SELECT_FAILED)
#define COM_ECODE_URL_RESOLVE_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_NET_FAILURE, CEC_URL_RESOLVE_FAILED)

#define COM_ECODE_MEM_VIOLATION CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_MEM_VIOLATION, CEC_MEM_VIOLATION)
#define COM_ECODE_MEM_SEG_FAULT CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_MEM_VIOLATION, CEC_MEM_SEG_FAULT)
#define COM_ECODE_MEM_BUS_ERROR CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_MEM_VIOLATION, CEC_MEM_BUS_ERROR)
#define COM_ECODE_MEM_BAD_ADDR CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_MEM_BAD_ADDR, CEC_MEM_BAD_ADDR)
#define COM_ECODE_MEM_MAP_FAILED CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_MEM_MAP_FAILED, CEC_MEM_MAP_FAILED)
#define COM_ECODE_MEM_UNMAP_FAILED CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_MEM_MAP_FAILED, CEC_MEM_UNMAP_FAILED)

#define COM_ECODE_AUTH_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_AUTH_FAILED)
#define COM_ECODE_NOT_VALID_PUBKEY CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_NOT_VALID_PUBKEY)
#define COM_ECODE_NOT_VALID_PRIKEY CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_NOT_VALID_PRIKEY)
#define COM_ECODE_NOT_VALID_TOKEN CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_NOT_VALID_TOKEN)
#define COM_ECODE_NOT_VALID_CERT CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_NOT_VALID_CERT)
#define COM_ECODE_NOT_VALID_SIGNATURE CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_NOT_VALID_SIGNATURE)
#define COM_ECODE_SIGN_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_SIGN_FAILED)
#define COM_ECODE_WRONG_PASSPHRASE CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_WRONG_PASSPHRASE)

#define COM_ECODE_DENY_SERVICE CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_DENY_SERVICE)

#define COM_ECODE_GEN_KEY_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_GEN_KEY_FAILED)
#define COM_ECODE_DERIVE_KEY_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_DERIVE_KEY_FAILED)
#define COM_ECODE_CRYPTO_COMPUTING_FAILED CECODE(CEC_INDI, CEC_SV_MAJOR, CEC_HD_ABORT, CEC_CAT_SEC_FAILURE, CEC_CRYPTO_COMPUTING_FAILED)

#define COM_ECODE_VER_ROLLBACK_DETECTED CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_SEC_ATTACK, CEC_VER_ROLLBACK_DETECTED)
#define COM_ECODE_REPLAY_DETECTED CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_SEC_ATTACK, CEC_REPLAY_DETECTED)
#define COM_ECODE_FLOODING_DETECTED CECODE(CEC_INDI, CEC_SV_CRITICAL, CEC_HD_ABORT, CEC_CAT_SEC_ATTACK, CEC_FLOODING_DETECTED)
#define COM_ECODE_LICENSE_CLONE_DETECTED CECODE(CEC_INDI, CEC_SV_FAFAL, CEC_HD_ABORT, CEC_CAT_SEC_ATTACK, CEC_LICENSE_CLONE_DETECTED)
#define COM_ECODE_MAN_IN_MIDDLE_DETECTED CECODE(CEC_INDI, CEC_SV_FAFAL, CEC_HD_ABORT, CEC_CAT_SEC_ATTACK, CEC_MAN_IN_MIDDLE_DETECTED)

#define COM_ECODE_PEER_CLOSE CECODE(0, 0, 0, 0, CEC_PEER_CLOSE)
#define COM_ECODE_COMPLETE CECODE(0, 0, 0, 0, CEC_COMPLETE)
#define COM_ECODE_TRY_AGAIN CECODE(0, 0, 0, 0, CEC_TRY_AGAIN)
#define COM_ECODE_NOT_MEET_REQUIREMENT CECODE(0, 0, 0, 0, CEC_NOT_MEET_REQUIREMENT)
#define COM_ECODE_NOT_FOUND_SKIP CECODE(0, 0, 0, 0, CEC_NOT_FOUND_SKIP)
#define COM_ECODE_INTERRUPT CECODE(0, 0, 0, 0, CEC_INTERRUPT)
#define COM_ECODE_SKIP_DUPLICATED CECODE(0, 0, 0, 0, CEC_SKIP_DUPLICATED)
#define COM_ECODE_NOT_NEEDED_SKIP CECODE(0, 0, 0, 0, CEC_NOT_NEEDED_SKIP)

#define COM_ECODE_HANDLE_MSG CECODE(0, 0, 0, 0, CEC_HANDLE_MSG)

#ifdef __cplusplus
}
#endif

#endif

