/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: AmShMem_Msg.h
  Source: /root/msg/AmShMem_Msg.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC_AMSHMEM_MSG_H
#define DDSC_AMSHMEM_MSG_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct AmShMem_Msg
{
  uint8_t dec_id;
  uint8_t slave_id;
  uint32_t frame_id;
  uint32_t buffer_index;
  uint32_t width;
  uint32_t height;
  uint32_t pitch;
  uint32_t data_format;
  uint64_t phys_y_addr;
  uint64_t phys_uv_addr;
  uint64_t playback_pts;
  uint64_t system_time;
} AmShMem_Msg;

extern const dds_topic_descriptor_t AmShMem_Msg_desc;

#define AmShMem_Msg__alloc() \
((AmShMem_Msg*) dds_alloc (sizeof (AmShMem_Msg)));

#define AmShMem_Msg_free(d,o) \
dds_sample_free ((d), &AmShMem_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_AMSHMEM_MSG_H */
