/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: FreeFrame_Msg.h
  Source: /root/gst-dds/dds-msgs/FreeFrame_Msg.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC_FREEFRAME_MSG_H
#define DDSC_FREEFRAME_MSG_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FreeFrame_Msg
{
  uint8_t msg_id;
  uint32_t frame_id;
  uint32_t buffer_index;
  uint64_t phys_y_addr;
  uint64_t phys_uv_addr;
  uint64_t playback_pts;
  uint64_t system_time;
} FreeFrame_Msg;

extern const dds_topic_descriptor_t FreeFrame_Msg_desc;

#define FreeFrame_Msg__alloc() \
((FreeFrame_Msg*) dds_alloc (sizeof (FreeFrame_Msg)));

#define FreeFrame_Msg_free(d,o) \
dds_sample_free ((d), &FreeFrame_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_FREEFRAME_MSG_H */
