#RTSP_STREAM_URL=rtsps://127.0.0.1:8554/test0
RTSP_USERNAME=user
RTSP_PASSWORD=password
## Notice the path should be absolute
RTSP_CA_CERT_PEM=/usr/share/ambarella/gst_rtsp_ssl/cert/gst_ca_cert.crt
RTSP_CERT_PEM=/usr/share/ambarella/gst_rtsp_ssl/cert/gst_client_cert.crt
RTSP_CERT_KEY=/usr/share/ambarella/gst_rtsp_ssl/cert/gst_client_key_dec.pem
